Add home screen, improve app structure, improve SafeAreaView
Konstantin9658/trackizer-rn pull request #6
Opened 2024-08-07 05:34 UTC by Konstantin9658

2024-08-07 08:53 UTC, mandarinka requested changes

2024-08-07 08:53 UTC, mandarinka commented on app/auth/_layout.tsx
> +  const paddingTop = Platform.OS === "android" ? 40 : 20;
это хорошо бы вынести куда-то и назвать так чтобы понятно было где такой отступ используется

2024-08-07 08:53 UTC, mandarinka commented on components/Button/styles.ts
> +    width: 120,
а если я передам текст, который будет длиннее чем для кнопочки в прогресс баре? задавать жестко размер кнопки не гибко (это относится к высоте тоже)

2024-08-07 08:53 UTC, mandarinka commented on components/SafeAreaContainer/SafeAreaContainer.tsx
> +  return <SafeAreaView {...rest}>{children}</SafeAreaView>;
этот компонент лишний, можно сразу оборачивать контент в SafeAreaView и передавать ему нужные пропсы, эффект будет тот же:
`<SafeAreaView edges={["top"]}>`

2024-08-07 08:53 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +                  backgroundColor: decorColor,
Этот параметр в реальной жизни не будет хранить бэк. Достаточно сделать компонент для отображения данных с возможностью управлять цветом полоски сверху. Эти цвета можно так же сразу заложить в компонент, наподобие variant у кнопки. В итоге выглядеть будет так:
```
<View style={styles.subs}>
  <SubsInfo value="" type="active"/>
  <SubsInfo value="" type="highest"/>
  <SubsInfo value="" type="lowest"/>
</View>
```

2024-08-07 08:53 UTC, mandarinka commented on screens/home/styles.ts
> +  },
это должно быть в стилях компонента ButtonSettings

2024-08-07 09:42 UTC, mandarinka requested changes

2024-08-07 09:42 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +    count: "$19.99",
так же цена обычно хранится числом с округлением до сотых

2024-08-07 11:39 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +                  backgroundColor: decorColor,
Т.е. данные для этих блоков будут вычисляться на фонте и нет необходимости в принципе делать map

2024-08-08 07:30 UTC, Konstantin9658 commented on components/Button/styles.ts
> +    width: 120,
я думаю это повод для отдельного реквеста, пока не стал исправлять в этом

2024-08-08 07:32 UTC, Konstantin9658 commented on screens/home/HomeScreen.tsx
> +    count: "$19.99",
ну вроде у нас по макету так, поэтому я так и сделал, если это критично я поправлю

2024-08-08 09:11 UTC, mandarinka commented on components/Button/styles.ts
> +    width: 120,
нет, я так не думаю. Убери фиксированную ширину и высоту и добавь обертке padding сверху и по краям согласно макету

2024-08-08 09:11 UTC, mandarinka commented on components/Button/styles.ts
> +    width: 120,
этого сейчас будет достаточно

2024-08-08 09:19 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +          <SubsInfo type="lowest" value="$5.99" />
$ бэк не будет отдавать в значении, только число, перенеси внутрь компонента пока

2024-08-08 09:28 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +          <SubsInfo type="lowest" value="$5.99" />
А для type давай объявим enum

2024-08-09 06:17 UTC, mandarinka approved these changes

2024-08-09 09:22 UTC, merged