Add: filter-tabs, state manager, dummy subs
Konstantin9658/trackizer-rn pull request #7
Opened 2024-08-12 06:59 UTC by Konstantin9658

2024-08-12 11:48 UTC, mandarinka requested changes

2024-08-12 11:48 UTC, mandarinka commented on screens/home/types.ts
> +  };
дата следующего платежа будет храниться в формате MM-DD (или даже YYYY-MM-DD) и в одном поле на бэке

2024-08-12 11:48 UTC, mandarinka commented on screens/home/components/Tabs/types.ts
> +}
этот enum нам может пригодиться при работе с бэком, давай значений сделаем с маленькой буквы: subs, upcoming

2024-08-12 11:48 UTC, mandarinka commented on screens/home/components/Tabs/styles.ts
> +    borderWidth: 1,
у не активного таба сейчас есть бордер черного цвета, по макету его быть не должно

2024-08-12 11:48 UTC, mandarinka commented on screens/home/components/Tabs/styles.ts
> +    position: "relative",
а разве position по умолчанию не relative уже? еще раз вручную не нужно это прописывать

2024-08-12 11:48 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +        <View style={styles.cards}>
Здесь нужно использовать FlatList https://reactnative.dev/docs/flatlist вместо View и map из соображений производительности производительности

2024-08-12 11:48 UTC, mandarinka commented on screens/home/components/SubsCard/styles.ts
> +    maxWidth: 328,
договорились убрать maxWidth

2024-08-12 11:48 UTC, mandarinka commented on screens/home/components/Tabs/styles.ts
> +    maxWidth: 328,
договорились убрать maxWidth

2024-08-13 10:11 UTC, Konstantin9658 commented on screens/home/components/SubsCard/styles.ts
> +    maxWidth: 328,
мы договорились после того как я вылил

2024-08-13 16:25 UTC, mandarinka commented on screens/home/components/SubsCard/styles.ts
> +    maxWidth: 328,
да это так) но коменты тут не для самоутверждения и не стоит воспринимать на личный счет, я подсветила тут чтобы не забылось не потерялось в череде сообщений в слаке

2024-08-15 06:08 UTC, Konstantin9658 commented on screens/home/components/SubsCard/styles.ts
> +    maxWidth: 328,
Не, ты что я ни в коем случае так не считаю, просто подумал ты ошиблась

2024-08-19 09:13 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +        <View style={styles.cards}>
надо убрать все старое ненужное

2024-08-19 09:13 UTC, mandarinka commented on screens/home/HomeScreen.tsx
> +        data={SUBSCRIPTIONS}
нужно добавить keyExtractor

2024-08-21 07:54 UTC, mandarinka approved these changes

2024-08-21 07:54 UTC, mandarinka commented on screens/home/consts.ts
> +    writeOffDay: new Date(2025, 0, 25, 0, 0, 0, 0),
бэкенд в таких случаях обычно отдает дату строкой или таймстемп
ладно, оставь как есть

2024-08-21 07:54 UTC, mandarinka commented on screens/home/consts.ts
> +    image: require("./images/spotify.png"),
это тоже невалидный варинат в реальном приложении, но пусть пока будет так

2024-08-21 08:43 UTC, Konstantin9658 commented on screens/home/consts.ts
> +    writeOffDay: new Date(2025, 0, 25, 0, 0, 0, 0),
@mandarinka а так я вроде переделал на строку

2024-08-21 08:44 UTC, Konstantin9658 commented on screens/home/consts.ts
> +    writeOffDay: new Date(2025, 0, 25, 0, 0, 0, 0),
<img width="428" alt="image" src="https://github.com/user-attachments/assets/3462f5e4-df3e-4e6f-a170-f59308d0f603">

2024-08-21 08:45 UTC, Konstantin9658 commented on screens/home/consts.ts
> +    image: require("./images/spotify.png"),
я попытался сделать тоже просто строкой, а уже где использую это поле делать require(image), но таким образом крашится приложение

2024-08-21 08:57 UTC, merged