Add tabs component, add dummy pages (only test)
Konstantin9658/trackizer-rn pull request #8
Opened 2024-08-26 13:42 UTC by Konstantin9658

2024-08-29 08:01 UTC, mandarinka requested changes

2024-08-29 08:01 UTC, mandarinka commented on app/(tabs)/_layout.tsx
> +const renderCustomTabBar = (props: BottomTabBarProps) => <TabBar {...props} />;
не вижу особого смысла выносить это из компонента: ф-я простая, стилистически логично оставить внутри по аналогии с Tabs.Screen

2024-08-29 08:01 UTC, mandarinka commented on app/_layout.tsx
> +          <Stack.Screen name="new-subs" />
страница добавления подписки должна быть модальным окном 
см подробнее тут [Modal screen using Expo Router](https://docs.expo.dev/router/advanced/modals/#modal-screen-using-expo-router)

2024-08-29 08:01 UTC, mandarinka commented on app/(tabs)/_layout.tsx
> +} from "@react-navigation/bottom-tabs";
роутер экспо уже под капотом имеет @react-navigation/bottom-tabs, давай не будем добавлять библиотеку дважды
для TabBar нужно будет самостоятельно описать интефейс

2024-08-29 08:01 UTC, mandarinka commented on components/TabBar/components/TabBg.tsx
> +  <Svg viewBox="0 0 329 55" width={329} height={55} fill="none" {...props}>
так делать фон для табов не пойдет, он должен тянуться по ширине экрана как это делает список подписок

2024-08-29 08:01 UTC, mandarinka commented on components/TabBar/components/TabButtons/styles.ts
> +    width: 65.8,
давай целое число укажем, 66

2024-08-29 08:01 UTC, mandarinka commented on components/TabBar/styles.ts
> +    maxWidth: 329,
табы должны тянуться вслед за экраном как список подписок

2024-08-29 08:01 UTC, mandarinka commented on components/TabBar/styles.ts
> +    width: 65.8,
тут тоже давай целое число укажем

2024-08-29 11:38 UTC, Konstantin9658 commented on components/TabBar/components/TabButtons/styles.ts
> +    width: 65.8,
центральная кнопка в таком случае будет не по центру, очень глаз режет

2024-08-30 06:37 UTC, mandarinka commented on components/TabBar/components/TabButtons/styles.ts
> +    width: 65.8,
звучит странно, как она может быть не по центру если ей задать соотвествующее позиционироваание? Возможно дело в фоне под кнопкой? его в любом случае надо переделать

2024-09-19 12:37 UTC, Konstantin9658 commented on app/_layout.tsx
> +          <Stack.Screen name="new-subs" />
сделаю в отдельном ПР, пока не понял как сделать это у себя

2024-10-04 06:32 UTC, mandarinka requested changes

2024-10-04 06:32 UTC, mandarinka commented on screens/tabs/home/HomeScreen.tsx
> +  const offsetBottom = currentTabsHeight + 30;
для чего понадобилось хранить высоту табов в сторе и почему +30?

2024-10-04 06:32 UTC, mandarinka commented on components/TabBar/components/TabButtons/TabButtons.tsx
> +  console.log(insets);
логи после от ладки надо убрать

2024-10-04 06:32 UTC, mandarinka commented on app/(tabs)/_layout.tsx
> +  },
это тоже надо убрать если с отладкой все

2024-10-04 09:21 UTC, Konstantin9658 commented on screens/tabs/home/HomeScreen.tsx
> +  const offsetBottom = currentTabsHeight + 30;
без 30 последний элемент будет на уровне с табом, это условно паддинг нижний (кстати может паддинг решит эту проблему?)

2024-10-07 13:20 UTC, mandarinka commented on screens/tabs/home/HomeScreen.tsx
> +  const offsetBottom = currentTabsHeight + 30;
думаю стоит попробовать

2024-12-02 06:40 UTC, Konstantin9658 commented on screens/tabs/home/HomeScreen.tsx
> +  const offsetBottom = currentTabsHeight + 30;
Да, добавил контейнеру паддинг

2024-12-04 06:59 UTC, merged